In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/hp/Documents/PFE_Project/data_p.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         9994 non-null   int64
 1   shipmode           9994 non-null   object
 2   sales              9994 non-null   float64
 3   quantity           9994 non-null   int64
 4   discount           9994 non-null   float64
 5   profit             9994 non-null   float64
 6   segment            9994 non-null   object
 7   region             9994 non-null   object
 8   state              9994 non-null   object
 9   subcategory        9994 non-null   object
 10  category           9994 non-null   object
 11  orderdate_day      9994 non-null   int64
 12  orderdate_weekday  9994 non-null   object
 13  orderdate_month    9994 non-null   int64
 14  orderdate_year     9994 non-null   int64
 15  shipdate_day       9994 non-null   int64
 16  shipdate_weekday   9994 non-null   object
 17  shipdate_month     9994 non-null   int64
 18  shipdate_year      9994 non-null   int64
 19  preparationtime    9994 non-null   int64
dtypes: float64(3), int64(9), object(8)
memory usage: 1.5+ MB

In [4]:
df.describe()

,Unnamed: 0,sales,quantity,discount,profit,orderdate_day,orderdate_month,orderdate_year,shipdate_day,shipdate_month,shipdate_year,preparationtime
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,229.858001,3.789574,0.156203,28.656896,15.601461,7.805683,2014.722934,15.829798,7.738043,2014.738743,3.958175
std,2885.163629,623.245101,2.225110,0.206452,234.260108,8.744958,3.287618,1.124039,8.803977,3.345842,1.127020,1.747567
min,1.000000,0.444000,1.000000,0.000000,-6599.978000,1.000000,1.000000,2013.000000,1.000000,1.000000,2013.000000,0.000000
25%,2499.250000,17.280000,2.000000,0.000000,1.728750,8.000000,5.000000,2014.000000,8.000000,5.000000,2014.000000,3.000000
50%,4997.500000,54.490000,3.000000,0.200000,8.666500,16.000000,9.000000,2015.000000,16.000000,9.000000,2015.000000,4.000000
75%,7495.750000,209.940000,5.000000,0.200000,29.364000,23.000000,11.000000,2016.000000,24.000000,11.000000,2016.000000,5.000000
max,9994.000000,22638.480000,14.000000,0.800000,8399.976000,31.000000,12.000000,2016.000000,31.000000,12.000000,2017.000000,7.000000

In [5]:
dupl = df.duplicated(subset = ['sales', 'quantity', 'profit', 'orderdate_day', 'orderdate_month', 'orderdate_year'], keep=False)
df.loc[dupl]

,Unnamed: 0,shipmode,sales,quantity,discount,profit,segment,region,state,subcategory,category,orderdate_day,orderdate_weekday,orderdate_month,orderdate_year,shipdate_day,shipdate_weekday,shipdate_month,shipdate_year,preparationtime
566,567,Standard Class,281.372,2,0.3,-12.0588,Home Office,East,Ohio,Chairs ...,Furniture,23,Dienstag,4,2013,27,Samstag,4,2013,4
573,574,Standard Class,281.372,2,0.3,-12.0588,Home Office,East,Ohio,Chairs ...,Furniture,23,Dienstag,4,2013,27,Samstag,4,2013,4
901,902,First Class,25.400,5,0.0,8.6360,Consumer,West,California,Furnishings ...,Furniture,5,Sonntag,7,2015,7,Dienstag,7,2015,2
903,904,Same Day,25.400,5,0.0,8.6360,Home Office,West,Washington,Furnishings ...,Furniture,5,Sonntag,7,2015,5,Sonntag,7,2015,0
1567,1568,Second Class,4.928,2,0.2,0.7392,Corporate,South,North Carolina,Furnishings ...,Furniture,5,Samstag,7,2014,10,Donnerstag,7,2014,5
1571,1572,Standard Class,4.928,2,0.2,0.7392,Corporate,South,North Carolina,Furnishings ...,Furniture,5,Samstag,7,2014,11,Freitag,7,2014,6
5758,5759,Standard Class,6.480,1,0.0,3.1104,Consumer,West,Nevada,Labels ...,Office Supplies,6,Samstag,12,2014,10,Mittwoch,12,2014,4
6330,6331,Second Class,12.960,2,0.0,6.2208,Consumer,East,New York,Paper ...,Office Supplies,5,Samstag,11,2016,10,Donnerstag,11,2016,5
6421,6422,Same Day,19.440,3,0.0,9.3312,Consumer,West,Washington,Paper ...,Office Supplies,11,Sonntag,9,2016,11,Sonntag,9,2016,0
6506,6507,Second Class,19.440,3,0.0,9.3312,Corporate,West,California,Paper ...,Office Supplies,11,Sonntag,9,2016,13,Dienstag,9,2016,2
6708,6709,Standard Class,12.960,2,0.0,6.2208,Consumer,West,California,Paper ...,Office Supplies,5,Samstag,11,2016,9,Mittwoch,11,2016,4
6963,6964,Standard Class,6.480,1,0.0,3.1104,Consumer,East,New York,Paper ...,Office Supplies,6,Samstag,12,2014,10,Mittwoch,12,2014,4

In [6]:
# here we deleted one of the 2 rows that have the same informations
df = df.drop(df[df['Unnamed: 0'] == 567 ].index)

In [7]:
df.loc[dupl]

,Unnamed: 0,shipmode,sales,quantity,discount,profit,segment,region,state,subcategory,category,orderdate_day,orderdate_weekday,orderdate_month,orderdate_year,shipdate_day,shipdate_weekday,shipdate_month,shipdate_year,preparationtime
573,574,Standard Class,281.372,2,0.3,-12.0588,Home Office,East,Ohio,Chairs ...,Furniture,23,Dienstag,4,2013,27,Samstag,4,2013,4
901,902,First Class,25.400,5,0.0,8.6360,Consumer,West,California,Furnishings ...,Furniture,5,Sonntag,7,2015,7,Dienstag,7,2015,2
903,904,Same Day,25.400,5,0.0,8.6360,Home Office,West,Washington,Furnishings ...,Furniture,5,Sonntag,7,2015,5,Sonntag,7,2015,0
1567,1568,Second Class,4.928,2,0.2,0.7392,Corporate,South,North Carolina,Furnishings ...,Furniture,5,Samstag,7,2014,10,Donnerstag,7,2014,5
1571,1572,Standard Class,4.928,2,0.2,0.7392,Corporate,South,North Carolina,Furnishings ...,Furniture,5,Samstag,7,2014,11,Freitag,7,2014,6
5758,5759,Standard Class,6.480,1,0.0,3.1104,Consumer,West,Nevada,Labels ...,Office Supplies,6,Samstag,12,2014,10,Mittwoch,12,2014,4
6330,6331,Second Class,12.960,2,0.0,6.2208,Consumer,East,New York,Paper ...,Office Supplies,5,Samstag,11,2016,10,Donnerstag,11,2016,5
6421,6422,Same Day,19.440,3,0.0,9.3312,Consumer,West,Washington,Paper ...,Office Supplies,11,Sonntag,9,2016,11,Sonntag,9,2016,0
6506,6507,Second Class,19.440,3,0.0,9.3312,Corporate,West,California,Paper ...,Office Supplies,11,Sonntag,9,2016,13,Dienstag,9,2016,2
6708,6709,Standard Class,12.960,2,0.0,6.2208,Consumer,West,California,Paper ...,Office Supplies,5,Samstag,11,2016,9,Mittwoch,11,2016,4
6963,6964,Standard Class,6.480,1,0.0,3.1104,Consumer,East,New York,Paper ...,Office Supplies,6,Samstag,12,2014,10,Mittwoch,12,2014,4

In [8]:
# here we convert the weekday from german to english so it would be easy to combine all the date columns in one column
df['orderdate_weekday'] = df['orderdate_weekday'].replace({'Montag': 'Monday', 'Dienstag': 'Tuesday', 'Mittwoch': 'Wednesday', 'Donnerstag': 'Thursday', 'Freitag': 'Friday', 'Samstag': 'Saturday', 'Sonntag': 'Sunday'})
df['shipdate_weekday'] = df['shipdate_weekday'].replace({'Montag': 'Monday', 'Dienstag': 'Tuesday', 'Mittwoch': 'Wednesday', 'Donnerstag': 'Thursday', 'Freitag': 'Friday', 'Samstag': 'Saturday', 'Sonntag': 'Sunday'})

In [9]:
df['order_date'] = pd.to_datetime(dict(day=df['orderdate_day'], month=df['orderdate_month'], year=df['orderdate_year']))
df['ship_date'] = pd.to_datetime(dict(day=df['shipdate_day'], month=df['shipdate_month'], year=df['shipdate_year']))

In [10]:
df = df.drop(columns = ['orderdate_day', 'orderdate_month', 'orderdate_year', 'shipdate_year', 'shipdate_day', 'shipdate_month', 'Unnamed: 0'])

In [11]:
df

,shipmode,sales,quantity,discount,profit,segment,region,state,subcategory,category,orderdate_weekday,shipdate_weekday,preparationtime,order_date,ship_date
0,First Class,825.174,9,0.30,-117.8820,Corporate,Central,Illinois,Bookcases ...,Furniture,Sunday,Tuesday,2,2016-09-04,2016-09-06
1,Standard Class,411.332,4,0.15,-4.8392,Consumer,West,California,Bookcases ...,Furniture,Friday,Tuesday,4,2014-09-05,2014-09-09
2,Same Day,411.332,4,0.15,-4.8392,Home Office,West,California,Bookcases ...,Furniture,Thursday,Thursday,0,2013-11-28,2013-11-28
3,First Class,241.960,2,0.00,33.8744,Consumer,South,Louisiana,Bookcases ...,Furniture,Monday,Tuesday,1,2016-05-30,2016-05-31
4,Standard Class,341.960,2,0.00,78.6508,Home Office,East,Rhode Island,Bookcases ...,Furniture,Tuesday,Tuesday,7,2013-12-31,2014-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,First Class,1097.544,7,0.20,123.4737,Corporate,Central,Texas,Phones ...,Technology,Wednesday,Friday,2,2015-12-09,2015-12-11
9990,First Class,979.950,5,0.00,284.1855,Consumer,East,Massachusetts,Phones ...,Technology,Friday,Sunday,2,2016-12-02,2016-12-04
9991,Standard Class,235.188,2,0.40,-43.1178,Corporate,East,Ohio,Phones ...,Technology,Sunday,Friday,5,2014-01-12,2014-01-17
9992,First Class,391.980,2,0.00,113.6742,Consumer,East,Delaware,Phones ...,Technology,Thursday,Saturday,2,2016-09-22,2016-09-24
9993,Standard Class,391.980,2,0.00,113.6742,Home Office,South,Kentucky,Phones ...,Technology,Sunday,Thursday,4,2013-01-06,2013-01-10

In [12]:
df.rename(columns = {'discount': 'discount_pct'}, inplace = True)
df

,shipmode,sales,quantity,discount_pct,profit,segment,region,state,subcategory,category,orderdate_weekday,shipdate_weekday,preparationtime,order_date,ship_date
0,First Class,825.174,9,0.30,-117.8820,Corporate,Central,Illinois,Bookcases ...,Furniture,Sunday,Tuesday,2,2016-09-04,2016-09-06
1,Standard Class,411.332,4,0.15,-4.8392,Consumer,West,California,Bookcases ...,Furniture,Friday,Tuesday,4,2014-09-05,2014-09-09
2,Same Day,411.332,4,0.15,-4.8392,Home Office,West,California,Bookcases ...,Furniture,Thursday,Thursday,0,2013-11-28,2013-11-28
3,First Class,241.960,2,0.00,33.8744,Consumer,South,Louisiana,Bookcases ...,Furniture,Monday,Tuesday,1,2016-05-30,2016-05-31
4,Standard Class,341.960,2,0.00,78.6508,Home Office,East,Rhode Island,Bookcases ...,Furniture,Tuesday,Tuesday,7,2013-12-31,2014-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,First Class,1097.544,7,0.20,123.4737,Corporate,Central,Texas,Phones ...,Technology,Wednesday,Friday,2,2015-12-09,2015-12-11
9990,First Class,979.950,5,0.00,284.1855,Consumer,East,Massachusetts,Phones ...,Technology,Friday,Sunday,2,2016-12-02,2016-12-04
9991,Standard Class,235.188,2,0.40,-43.1178,Corporate,East,Ohio,Phones ...,Technology,Sunday,Friday,5,2014-01-12,2014-01-17
9992,First Class,391.980,2,0.00,113.6742,Consumer,East,Delaware,Phones ...,Technology,Thursday,Saturday,2,2016-09-22,2016-09-24
9993,Standard Class,391.980,2,0.00,113.6742,Home Office,South,Kentucky,Phones ...,Technology,Sunday,Thursday,4,2013-01-06,2013-01-10

In [13]:
df['discount_pct'] = df['discount_pct'] * 100

In [14]:
df['profit_pct'] = (df['profit'] / df['sales']) * 100
df

,shipmode,sales,quantity,discount_pct,profit,segment,region,state,subcategory,category,orderdate_weekday,shipdate_weekday,preparationtime,order_date,ship_date,profit_pct
0,First Class,825.174,9,30.0,-117.8820,Corporate,Central,Illinois,Bookcases ...,Furniture,Sunday,Tuesday,2,2016-09-04,2016-09-06,-14.285714
1,Standard Class,411.332,4,15.0,-4.8392,Consumer,West,California,Bookcases ...,Furniture,Friday,Tuesday,4,2014-09-05,2014-09-09,-1.176471
2,Same Day,411.332,4,15.0,-4.8392,Home Office,West,California,Bookcases ...,Furniture,Thursday,Thursday,0,2013-11-28,2013-11-28,-1.176471
3,First Class,241.960,2,0.0,33.8744,Consumer,South,Louisiana,Bookcases ...,Furniture,Monday,Tuesday,1,2016-05-30,2016-05-31,14.000000
4,Standard Class,341.960,2,0.0,78.6508,Home Office,East,Rhode Island,Bookcases ...,Furniture,Tuesday,Tuesday,7,2013-12-31,2014-01-07,23.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,First Class,1097.544,7,20.0,123.4737,Corporate,Central,Texas,Phones ...,Technology,Wednesday,Friday,2,2015-12-09,2015-12-11,11.250000
9990,First Class,979.950,5,0.0,284.1855,Consumer,East,Massachusetts,Phones ...,Technology,Friday,Sunday,2,2016-12-02,2016-12-04,29.000000
9991,Standard Class,235.188,2,40.0,-43.1178,Corporate,East,Ohio,Phones ...,Technology,Sunday,Friday,5,2014-01-12,2014-01-17,-18.333333
9992,First Class,391.980,2,0.0,113.6742,Consumer,East,Delaware,Phones ...,Technology,Thursday,Saturday,2,2016-09-22,2016-09-24,29.000000
9993,Standard Class,391.980,2,0.0,113.6742,Home Office,South,Kentucky,Phones ...,Technology,Sunday,Thursday,4,2013-01-06,2013-01-10,29.000000

In [15]:
df.to_csv('Sales_Data.csv', index = False)

In [16]:
DF.to_csv('FAQs.csv', index = False)

NameError: name 'DF' is not defined

In [21]:
total_am = df.groupby('state')['sales'].sum()
total_am

state
Alabama                  19510.6400
Arizona                  35282.0010
Arkansas                 11678.1300
California              457687.6315
Colorado                 32108.1180
Connecticut              13384.3570
Delaware                 27451.0690
District of Columbia      2865.0200
Florida                  89473.7080
Georgia                  49095.8400
Idaho                     4382.4860
Illinois                 80166.1010
Indiana                  53555.3600
Iowa                      4579.7600
Kansas                    2914.3100
Kentucky                 36591.7500
Louisiana                 9217.0300
Maine                     1270.5300
Maryland                 23705.5230
Massachusetts            28634.4340
Michigan                 76269.6140
Minnesota                29863.1500
Mississippi              10771.3400
Missouri                 22205.1500
Montana                   5589.3520
Nebraska                  7464.9300
Nevada                   16729.1020
New Hampshire             7292.5240
New Jersey               35764.3120
New Mexico                4783.5220
New York                310876.2710
North Carolina           55603.1640
North Dakota               919.9100
Ohio                     77976.7640
Oklahoma                 19683.3900
Oregon                   17431.1500
Pennsylvania            116511.9140
Rhode Island             22627.9560
South Carolina            8481.7100
South Dakota              1315.5600
Tennessee                30661.8730
Texas                   170188.0458
Utah                     11220.0560
Vermont                   8929.3700
Virginia                 70636.7200
Washington              138641.2700
West Virginia             1209.8240
Wisconsin                32114.6100
Wyoming                   1603.1360
Name: sales, dtype: float64

In [18]:
date= df['order_date'].dt.year
df.groupby(date)['sales'].sum()

order_date
2013    483966.1261
2014    470532.5090
2015    608473.8300
2016    733947.0232
Name: sales, dtype: float64